### ISSUE TITLE
sort out `rjags` and `JAGS` version that work on corporate laptop

### ISSUE THREAD

**Issue by papsti** [phac-nml-phrsd/ern#128]
possible solutions to the issue of getting all dependencies working for our packages (rjags and JAGS) on the corporate laptop:

1. have R 4.2.2 and JAGS 4.3.1 made available on service gateway---@papsti following up on this
2. see if downgrading to R 4.1 works with JAGS 4.2 (currently available on software gateway)---@wyusuf068 following up on this

**Comment by papsti** [comment]
based on [this info](https://martynplummer.wordpress.com/2022/04/12/windows-update-jags-4-3-1-is-released/), we at least need JAGS upgraded to 4.3.1 on service gateway to be compatible with R 4.2.x. i'll see how soon we can get that done

it also seems plausible that downgrading R to 4.1 will work with JAGS 4.2 (on service gateway)

**Comment by wyusuf068** [comment]
JAGS 4.2 works on R 4.1.1. Instructions on what do if user cannot install latest JAGS version specified in #131.
