### ISSUE TITLE
increase iterations/other run parameters in vignettes once main development is done

### ISSUE THREAD

**Issue by papsti** [phac-nml-phrsd/ern#134]
in clinical vignette, using a small number of Rt iterations, 1 MCMC chain for agg -> daily inference, small burn-in and iteration numbers for MCMC, just to make vignette compile faster when running `devtools::check()`

should increase this when we're done with the bulk of development (after v1.1?)

**Comment by davidchampredon** [comment]
See #181. We have to keep the computation time in mind...
