### ISSUE TITLE
merge ww and clinical vignettes into one about estimating Rt?

### ISSUE THREAD

**Issue by papsti** [phac-nml-phrsd/ern#144]
in reviewing @wyusuf068 suggestions for my edits to the ww vignette (thank you!), i realized that there will likely be a bunch of redundancy between the ww and cl vignettes, because the general approach is the same: input signal -> inferred incidence -> Rt. the main difference is in the inputs and the first step (to get to inferred incidence). 

@davidchampredon, @wyusuf068, i propose instead of having two vignettes we just do one on "calculating Rt", with the following structure:

1. general introduction to estimating Rt with `ern`
     a. introducing the two main functions `estimate_R_xx()` + mentioning that the package features two methods for estimating Rt: from ww concentration and from the clinical data
     b. outlining the general structure of the code as in two parts (1) input data -> inferred incidence and (2) inferred incidence -> Rt, making it clear that part (2) is common to both ww and cl computations, while the difference lies in part (1)
2. details of part (2) the incidence to R calculation via `EpiEstim` + settings therein
3. details of part (1) for each data source
     a. ww details
          1. overview of ww to incidence calculation (describe procedure)
          2. demo of ww to Rt calculation, including required inputs + their formats, description of output object, demo of plotting method
     b. cl details
     
while this order is less in sync with how one puts arguments into the `estimate_R_xx()` funs (which is how the vignette is currently structured), i think it cuts down on redundancy and gives the user a much better "big picture" overview of the software. the former approach is essentially already covered by the documentation in `estimate_R_xx()`, while this approach is perhaps a bit more narrative.

i'd like to discuss this before making further progress on #143 and #120

**Comment by wyusuf068** [comment]
@papsti I like this proposal. I would suggest in the first part of the vignette a general workflow chart illustrating how to go from clinical reports/ww concentration to $R_t$ and showing a convergence of the pipeline once inferred incidence is obtained.

**Comment by papsti** [comment]
wonderful! we can use the flowcharts that @davidchampredon developed/updated a little while ago, even just as a starting point?

**Comment by davidchampredon** [comment]
Good idea, @papsti about the single vignette.
