### ISSUE TITLE
crop output consistently between `ww` and `cl`

### ISSUE THREAD

**Issue by papsti** [phac-nml-phrsd/ern#170]
the latest `ww.input` data starts on 2023-07-23, but when one uses `estimate_Rt_ww()` followed by `plot_diagnostic_ww()`, the result is a series of plots that starts after 1 Aug:

![image](https://github.com/phac-nml-phrsd/ern/assets/21325059/6573240a-c487-45ae-be86-68a26b456908)

@wyusuf068 what is the internal rule for cropping the start of the timeseries, which i assume happens because the method we're using to calculate Rt is not reliable at the start of the ts? on the clinical side, i wasn't cropping, i was just plotting the points within one generation interval of the start of the data (using the max value of the truncated family) with a dotted line + lighter confidence interval band:

![image](https://github.com/phac-nml-phrsd/ern/assets/21325059/784d5761-d99e-489d-9736-5c5bbcc2c4c3)

i'd prefer to crop like is done on the ww side, but we should probably use the same heuristic.

**Comment by davidchampredon** [comment]
The crop does not occur in the `plot` part. I believe the start and end dates for Rt estimation are actually determined by `EpiEstim` function. Not 100% sure, @wyusuf068 will know better.

**Comment by wyusuf068** [comment]
The cropping of the concentration data in the time-series _does_ occur in `plot_diagnostic_ww()` to line up with the first output date of the `EpiEstim` Rt calculation. @papsti see [here](https://github.com/phac-nml-phrsd/ern/blob/main/R/plot.R#L24) on it's done on the WW side.

**Comment by davidchampredon** [comment]
oh gosh - sorry about the confusion @wyusuf068
But isn't the start date determined by `EpiEstim`?
`date.start = min(r.estim$R$date)` (line 15 just above)

I understand @papsti wants to see if she can replicate this on the clinical side (unless I missed something again!)

**Comment by wyusuf068** [comment]
> oh gosh - sorry about the confusion @wyusuf068 But isn't the start date determined by `EpiEstim`? `date.start = min(r.estim$R$date)` (line 15 just above)
> 
> I understand @papsti wants to see if she can replicate this on the clinical side (unless I missed something again!)

Yes. So any time-series values before the start date of the `EpiEstim` output are cropped.

**Comment by papsti** [comment]
OK, i will do the same thing on the clinical side and remove the dotted plotting at the start of the Rt timeseries

**Comment by papsti** [comment]
i still have an issue at the start of the Rt timeseries. i thought it might have to do with the sample data i chose, but even if i choose data where cases are initially decreasing, is till get really high Rt estimates to start:

![image](https://github.com/phac-nml-phrsd/ern/assets/21325059/212745e2-aa70-4815-8e05-41c901297797)

(the crop is trickier with clinical data that can be aggregate (_e.g._ weekly) to start, so i've just used coord_cartesian to match the x-axes to the Rt output)
