### ISSUE TITLE
regenerate pkg vignettes using manscript

### ISSUE THREAD

**Issue by papsti** [phac-nml-phrsd/ern#173]
be sure to update values shipped with `def_dist_fecal_shedding()` when vignettes get regeneraged

**Comment by davidchampredon** [comment]
Also see #181 regarding the computing time when generating the vignettes

**Comment by davidchampredon** [comment]
This issue was relevant when we wanted to publish with JSS. Not relevant any more.

**Comment by papsti** [comment]
I think there is some value with synchronizing the content of the ms with the package vignettes. They both have a similar goal, but we spent a lot more time refining the presentation in the ms.
