### ISSUE TITLE
split out `plot_diagnostic_xx()` funs for individual panels

### ISSUE THREAD

**Issue by papsti** [phac-nml-phrsd/ern#194]
make funs for each individual panel user-facing (simple with proper documentation) and ensure `plot_diagnostic_xx()` is just a convenience wrapper function around each of the panel funs (no additional plotting magic here except composing via `patchwork`).

**Comment by davidchampredon** [comment]
done in commit 2c923547cc1f8ef645ccddc919154d8c91d0d81c
