### ISSUE TITLE
figure out why `set.seed(i)` was necessary to ensure random gi sampling for ww test code

### ISSUE THREAD

**Issue by papsti** [phac-nml-phrsd/ern#76]
as done in 936302a

**Comment by davidchampredon** [comment]
I did some tests and it turns out that we do not have to call `set.seed()`, the function `sample_a_dist` that calls the `rgamma`, `rlnorm`, etc. does the job well. There was just on occurrence of a `set.seed` left over and i deleted it in 17510c6
