### ISSUE TITLE
make updated summary diagram of the main steps in `estimate_R_cl()` and `estimate_R_ww()`

### ISSUE THREAD

**Issue by papsti** [phac-nml-phrsd/ern#80]
currently we have this diagram that illustrates the main steps in the calculation of Rt from both clinical and wastewater input data:

![image](https://user-images.githubusercontent.com/21325059/217921319-185ad8a8-8f0a-460f-93e3-b0e71c19fc53.png)

we should make an updated version of this diagram that has a bit more detail about how these calculations are conducted within the `ern` repo, for instance where sampling (of distributions or timeseries) happens and where major `ern` functions come into play. here is a sketch from which to develop this updated diagram:

![image](https://user-images.githubusercontent.com/21325059/217929746-75b8e719-c913-4c88-b36b-3b8e8495586b.png)

**Comment by davidchampredon** [comment]
Done in [manuscript](https://gitlab.cscscience.ca/phrsd/risk/ern-ms)

**Comment by papsti** [comment]
should we add the image to this repo README?
